const UserTypes = {
  CREATE_USER_OBJECT: 'CREATE_USER_OBJECT',
  CREATE_USER_ERROR_OBJECT: 'CREATE_USER_ERROR_OBJECT',
  CREATE_USER_OBJECTS: 'CREATE_USER_OBJECTS',
  FEATCH_USER_OBJECT: 'FEATCH_USER_OBJECT',
  FETCHING_OBJECT: 'FETCHING_OBJECT',
};

export default UserTypes;
